{% set name = "napari-czann-segment" %}
{% set version = "0.0.17" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-czann-segment-{{ version }}.tar.gz
  sha256: 0c35fef64e07aa5a6e5c74603f40cb55b00d0e72492e777378ee0b6e2f9e68c1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - aicsimageio
    - czmodel >=5
    - cztile
    - dask-core
    - magicgui
    - napari
    - numpy
    - onnxruntime
    - python >={{ python_min }}
    - pytorch
    - qtpy
    - scikit-image
    - tifffile >=2023.4.12
    - tqdm

test:
  imports:
    - napari_czann_segment
  commands:
    - pip list
    # - pip check 
  requires:
    - pip
    - pyqt
    - python {{ python_min }}

about:
  home: https://pypi.org/project/napari-czann-segment
  summary: Segmention using DeepLearning ONNX models packaged as *.czann files
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/sebi06/napari-czann-segment

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - sebi06
